import { type NextPage } from "next";
import Head from "next/head";
import {
  CCol,
  CRow,
  CTable,
  CTableBody,
  CTableCaption,
  CTableDataCell,
  CTableHead,
  CTableHeaderCell,
  CTableRow,
} from "@coreui/react-pro"

import { api } from "~/utils/api";
import Link from "next/link";

const Home: NextPage = () => {
  const { data } = api.example.getData.useQuery(undefined);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Test</h1>
        <Link href="/">Home</Link>
        {!!data && <CTable>
          <CTableCaption>Data Points</CTableCaption>
          <CTableHead>
            <CTableRow>
              <CTableHeaderCell>Tempearture</CTableHeaderCell>
              <CTableHeaderCell>Humidity</CTableHeaderCell>
              <CTableHeaderCell>Co2</CTableHeaderCell>
              <CTableHeaderCell>PH</CTableHeaderCell>
              <CTableHeaderCell>Timestamp</CTableHeaderCell>
            </CTableRow>
          </CTableHead>
          <CTableBody>
            {data.map((data, index) => (
              <CTableRow key={index}>
                <CTableDataCell>{data.temperature}</CTableDataCell>
                <CTableDataCell>{data.humidity}</CTableDataCell>
                <CTableDataCell>{data.CO2}</CTableDataCell>
                <CTableDataCell>{data.PH}</CTableDataCell>
                <CTableDataCell>{data.updated_at?.toLocaleString()}</CTableDataCell>
              </CTableRow>
            ))}
          </CTableBody>
        </CTable>}
                        
      </main>
    </>
  );
};

export default Home;
